# Attach to a tmux session if it exists, otherwise create a new one
# inside of a glorious fish shell
shell:
  program: /Users/slink/.nix-profile/bin/fish
  args:
    - -l
    - -c
    - "tmux attach || tmux"

scrolling:
  history: 1000
  multiplier: 3

window:
  opacity: 0.9
  padding:
    x: 10
    y: 10

font:
  size: 18.0
  normal:
    family: Fira Code Retina

colors:
  primary:
    background: "#2E3440"
    foreground: "#D8DEE9"

  normal:
    black: "#3B4252"
    red: "#BF616A"
    green: "#A3BE8C"
    yellow: "#EBCB8B"
    blue: "#81A1C1"
    magenta: "#B48EAD"
    cyan: "#88C0D0"
    white: "#E5E9F0"

  bright:
    black: "#4C566A"
    red: "#BF616A"
    green: "#A3BE8C"
    yellow: "#EBCB8B"
    blue: "#81A1C1"
    magenta: "#B48EAD"
    cyan: "#8FBCBB"
    white: "#ECEFF4"
