tap "homebrew/cask"
tap "caskroom/cask"
tap "homebrew/bundle"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "mongodb/brew"

brew "fish"
brew "go"
brew "vim"
brew "postgresql"
brew "wget"
brew "jq"
brew "thefuck"
brew "htop"
brew "docker"
brew "mongodb-community"

cask "postico"
cask "spotify"
#cask "1password"
#cask "microsoft-office"
#cask "microsoft-teams"
cask "font-fira-code"
#cask "brave-browser"
#cask "virtualbox"
cask "visual-studio-code"
