tap "homebrew/cask"
tap "caskroom/cask"
tap "homebrew/bundle"
tap "homebrew/cask-fonts"
tap "homebrew/core"

brew "fish"
brew "go"
brew "vim"
brew "postgresql"
brew "wget"
brew "jq"

cask "postico"
cask "1password"
cask "microsoft-office"
cask "microsoft-teams"
cask "font-fira-code"
cask "brave-browser"
cask "virtualbox"
cask "visual-studio-code"