#!/bin/bash

code --install-extension aaron-bond.better-comments
code --install-extension alexkrechik.cucumberautocomplete
code --install-extension bierner.markdown-mermaid
code --install-extension christian-kohler.npm-intellisense
code --install-extension CoenraadS.bracket-pair-colorizer
code --install-extension DanSnow.vscode-dockerfilelint
code --install-extension DavidAnson.vscode-markdownlint
code --install-extension davidhewitt.shebang-language-associator
code --install-extension eamodio.gitlens
code --install-extension eg2.vscode-npm-script
code --install-extension Equinusocio.vsc-material-theme
code --install-extension esbenp.prettier-vscode
code --install-extension Gruntfuggly.todo-tree
code --install-extension httpsterio.henna
code --install-extension joelday.docthis
code --install-extension kisstkondoros.vscode-codemetrics
code --install-extension marcoq.vscode-typescript-to-json-schema
code --install-extension mike-lischke.vscode-antlr4
code --install-extension mikestead.dotenv
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-vscode.vscode-typescript-tslint-plugin
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension mscgenjs.vscode-mscgen
code --install-extension pflannery.vscode-versionlens
code --install-extension PKief.material-icon-theme
code --install-extension quicktype.quicktype
code --install-extension shardulm94.trailing-spaces
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension wraith13.unsaved-files-vscode