import chalk from "chalk";
import { readdir } from "node:fs/promises";
import { join } from "node:path";
import { log, runQuiet, DOTFILES_DIR } from "./utils";

interface ThemeDef {
  name: string;
  slug: string;
  nvim: {
    plugin: string;
    colorscheme: string;
    style: string;
    transparent: boolean;
  };
  bat: {
    syntaxTheme: string;
  };
  colors: Record<string, string>;
}

interface TemplateEntry {
  template: string;
  output: string;
}

const THEMES_DIR = join(DOTFILES_DIR, "themes");
const ACTIVE_FILE = join(THEMES_DIR, "active.txt");

// All template -> output mappings
const TEMPLATES: TemplateEntry[] = [
  {
    template: "alacritty/alacritty.toml.tmpl",
    output: "alacritty/alacritty.toml",
  },
  {
    template: "tmux/tmux.conf.tmpl",
    output: "tmux/tmux.conf",
  },
  {
    template: "nvim/lua/options.lua.tmpl",
    output: "nvim/lua/options.lua",
  },
  {
    template: "nvim/lua/plugins/scrollbar.lua.tmpl",
    output: "nvim/lua/plugins/scrollbar.lua",
  },
  {
    template: "lazygit/config.yml.tmpl",
    output: "lazygit/config.yml",
  },
];

/** Resolve a dot-path like "colors.bg" against the theme object */
function resolve(obj: Record<string, unknown>, path: string): string {
  const parts = path.split(".");
  let current: unknown = obj;
  for (const part of parts) {
    if (current == null || typeof current !== "object") return `{{${path}}}`;
    current = (current as Record<string, unknown>)[part];
  }
  return String(current);
}

/** Render a template string with theme values */
function render(template: string, theme: ThemeDef): string {
  return template.replace(/\{\{(\w+(?:\.\w+)*)\}\}/g, (match, path) => {
    // Skip lazygit's own {{filename}} placeholder
    if (path === "filename") return match;
    return resolve(theme as unknown as Record<string, unknown>, path);
  });
}

export async function getAvailableThemes(): Promise<ThemeDef[]> {
  const files = await readdir(THEMES_DIR);
  const themes: ThemeDef[] = [];
  for (const file of files) {
    if (!file.endsWith(".json")) continue;
    const content = await Bun.file(join(THEMES_DIR, file)).json();
    themes.push(content as ThemeDef);
  }
  return themes.sort((a, b) => a.name.localeCompare(b.name));
}

export async function getActiveSlug(): Promise<string> {
  const file = Bun.file(ACTIVE_FILE);
  if (await file.exists()) {
    return (await file.text()).trim();
  }
  return "tokyo-night";
}

export async function getActiveTheme(): Promise<ThemeDef> {
  const slug = await getActiveSlug();
  const file = Bun.file(join(THEMES_DIR, `${slug}.json`));
  if (!(await file.exists())) {
    throw new Error(`Theme "${slug}" not found`);
  }
  return file.json() as Promise<ThemeDef>;
}

export async function generateConfigs(theme: ThemeDef): Promise<void> {
  // Render all templates
  for (const entry of TEMPLATES) {
    const templatePath = join(DOTFILES_DIR, entry.template);
    const outputPath = join(DOTFILES_DIR, entry.output);
    const template = await Bun.file(templatePath).text();
    const rendered = render(template, theme);
    await Bun.write(outputPath, rendered);
  }

  // Generate nvim/lua/theme-active.lua
  const nvimTheme = `-- DO NOT EDIT — generated by theme engine
return {
  colorscheme = "${theme.nvim.colorscheme}",
  style = "${theme.nvim.style}",
  transparent = ${theme.nvim.transparent},
}
`;
  await Bun.write(join(DOTFILES_DIR, "nvim/lua/theme-active.lua"), nvimTheme);
}

export async function reloadRunningApps(): Promise<void> {
  // Reload tmux if running
  try {
    await runQuiet(["tmux", "source-file", `${process.env.HOME}/.tmux.conf`]);
    log.success("Reloaded tmux");
  } catch {
    // tmux not running, that's fine
  }

  // Rebuild bat cache for delta
  try {
    await runQuiet(["bat", "cache", "--build"]);
    log.success("Rebuilt bat cache");
  } catch {
    // bat not installed, that's fine
  }

  // Alacritty auto-reloads on config change — no action needed
  // Lazygit picks up changes on next launch — no action needed
}

export async function setActiveTheme(slug: string): Promise<void> {
  const themes = await getAvailableThemes();
  const theme = themes.find((t) => t.slug === slug);
  if (!theme) {
    const available = themes.map((t) => t.slug).join(", ");
    throw new Error(`Unknown theme "${slug}". Available: ${available}`);
  }

  await Bun.write(ACTIVE_FILE, slug + "\n");
  log.step(`Switching to ${theme.name}`);

  await generateConfigs(theme);
  log.success("Generated config files");

  await reloadRunningApps();
  log.success(`Theme set to ${chalk.bold(theme.name)}`);
}

export async function listThemes(): Promise<void> {
  const themes = await getAvailableThemes();
  const active = await getActiveSlug();

  console.log(chalk.bold("\n  Available themes:\n"));
  for (const theme of themes) {
    const marker = theme.slug === active ? chalk.green(" ● ") : "   ";
    const name =
      theme.slug === active
        ? chalk.bold.green(theme.name)
        : chalk.white(theme.name);
    const slug = chalk.gray(`(${theme.slug})`);
    const swatch = Object.values(theme.colors)
      .slice(0, 8)
      .map((c) => chalk.hex(c)("█"))
      .join("");
    console.log(`${marker}${name} ${slug}  ${swatch}`);
  }
  console.log();
  console.log(chalk.gray(`  Usage: theme <slug>`));
  console.log();
}
